// <auto-generated />
using System;
using ExecutionService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ExecutionService.Migrations
{
    [DbContext(typeof(ExecutionDbContext))]
    [Migration("20260427060825_ChangeToLocalTime")]
    partial class ChangeToLocalTime
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ExecutionService.Models.ExecutionJob", b =>
                {
                    b.Property<Guid>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ExecutionTimeMs")
                        .HasColumnType("bigint");

                    b.Property<int?>("ExitCode")
                        .HasColumnType("int");

                    b.Property<int>("FileId")
                        .HasColumnType("int");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("MemoryUsedKb")
                        .HasColumnType("bigint");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.Property<string>("SourceCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Stderr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stdin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Stdout")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("JobId");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.ToTable("ExecutionJobs");
                });

            modelBuilder.Entity("ExecutionService.Models.SupportedLanguage", b =>
                {
                    b.Property<int>("LanguageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LanguageId"));

                    b.Property<string>("DockerImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileExtension")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LanguageId");

                    b.ToTable("SupportedLanguages");

                    b.HasData(
                        new
                        {
                            LanguageId = 1,
                            DockerImage = "python:3.11-slim",
                            FileExtension = ".py",
                            IsEnabled = true,
                            Name = "Python",
                            Version = "3.11"
                        },
                        new
                        {
                            LanguageId = 2,
                            DockerImage = "node:20-slim",
                            FileExtension = ".js",
                            IsEnabled = true,
                            Name = "JavaScript",
                            Version = "20.0"
                        },
                        new
                        {
                            LanguageId = 3,
                            DockerImage = "openjdk:17-slim",
                            FileExtension = ".java",
                            IsEnabled = true,
                            Name = "Java",
                            Version = "17.0"
                        },
                        new
                        {
                            LanguageId = 4,
                            DockerImage = "gcc:13-slim",
                            FileExtension = ".c",
                            IsEnabled = true,
                            Name = "C",
                            Version = "13.0"
                        },
                        new
                        {
                            LanguageId = 5,
                            DockerImage = "gcc:13-slim",
                            FileExtension = ".cpp",
                            IsEnabled = true,
                            Name = "C++",
                            Version = "13.0"
                        },
                        new
                        {
                            LanguageId = 6,
                            DockerImage = "golang:1.21-slim",
                            FileExtension = ".go",
                            IsEnabled = true,
                            Name = "Go",
                            Version = "1.21"
                        },
                        new
                        {
                            LanguageId = 7,
                            DockerImage = "rust:1.74-slim",
                            FileExtension = ".rs",
                            IsEnabled = true,
                            Name = "Rust",
                            Version = "1.74"
                        },
                        new
                        {
                            LanguageId = 8,
                            DockerImage = "node:20-slim",
                            FileExtension = ".ts",
                            IsEnabled = true,
                            Name = "TypeScript",
                            Version = "5.0"
                        },
                        new
                        {
                            LanguageId = 9,
                            DockerImage = "php:8.2-cli",
                            FileExtension = ".php",
                            IsEnabled = true,
                            Name = "PHP",
                            Version = "8.2"
                        },
                        new
                        {
                            LanguageId = 10,
                            DockerImage = "ruby:3.2-slim",
                            FileExtension = ".rb",
                            IsEnabled = true,
                            Name = "Ruby",
                            Version = "3.2"
                        },
                        new
                        {
                            LanguageId = 11,
                            DockerImage = "openjdk:17-slim",
                            FileExtension = ".kt",
                            IsEnabled = true,
                            Name = "Kotlin",
                            Version = "1.9"
                        },
                        new
                        {
                            LanguageId = 12,
                            DockerImage = "swift:5.9-slim",
                            FileExtension = ".swift",
                            IsEnabled = true,
                            Name = "Swift",
                            Version = "5.9"
                        },
                        new
                        {
                            LanguageId = 13,
                            DockerImage = "r-base:4.3",
                            FileExtension = ".r",
                            IsEnabled = true,
                            Name = "R",
                            Version = "4.3"
                        },
                        new
                        {
                            LanguageId = 14,
                            DockerImage = "mcr.microsoft.com/dotnet/sdk:8.0",
                            FileExtension = ".cs",
                            IsEnabled = true,
                            Name = "CSharp",
                            Version = "8.0"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
